#!/bin/bash

#asks for filename
echo "Enter file name:"
read file_name

#creates stemmed file
cat ../DataProject/data/Finnish/$file_name | python ../DataProject/Finnish/preproc_Finland.py | python ../DataProject/Finnish/finnish_stemmer.py > ../DataProject/data/Finnish/results/stemmed/$file_name

#creates attribute list
cat ../DataProject/data/Finnish/$file_name | python ../DataProject/Finnish/Finntagger_preproc.py | ftb-label | python ../DataProject/Finnish/adjfreq.py | python ../DataProject/Finnish/Finnish_attr_lister.py > ../DataProject/data/Finnish/results/attributes/$file_name-adj

#creates ARFF file for clustering
python ../DataProject/Finnish/adj-noun-clustering_arff_creator.py "../DataProject/data/Finnish/results/stemmed/$file_name" "../DataProject/data/Finnish/results/attributes/$file_name-adj" "../DataProject/data/Finnish/results/attributes/$file_name" "$file_name" > ../DataProject/data/Finnish/results/$file_name\_adj-noun-clustering.arff
