#!/bin/bash

#asks for filename
echo "Enter file name:"
read file_name

#creates stemmed file
cat data/Finnish/$file_name | python Finnish/preproc_Finland.py | python Finnish/finnish_stemmer.py > data/Finnish/results/stemmed/$file_name

#creates attribute list
cd Tools/FinnPos
cat ../../data/Finnish/$file_name | python ../../Finnish/Finntagger_preproc.py | ftb-label | python ../../Finnish/adjfreq.py | python ../../Finnish/Finnish_attr_lister.py > ../../data/Finnish/results/attributes/$file_name-adj
cd ..
cd ..

#creates ARFF file for clustering
python Finnish/adj-noun-clustering_arff_creator.py "data/Finnish/results/stemmed/$file_name" "data/Finnish/results/attributes/$file_name-adj" "data/Finnish/results/attributes/$file_name" "$file_name" > data/Finnish/results/$file_name\_adj-noun-clustering.arff
