#!/bin/bash

#asks for filename
echo "Enter file name:"
read file_name

#creates stemmed file
cat ../DataProject/data/Finnish/$file_name | python ../DataProject/Finnish/preproc_Finland.py | python ../DataProject/Finnish/finnish_stemmer.py > ../DataProject/data/Finnish/results/stemmed/$file_name

#creates attribute list
cat ../DataProject/data/Finnish/$file_name | python ../DataProject/Finnish/Finntagger_preproc.py | ftb-label | python ../DataProject/Finnish/Finnish_nounfreq.py | python ../DataProject/Finnish/Finnish_attr_lister.py > ../DataProject/data/Finnish/results/attributes/$file_name

#creates ARFF file for association rule testing
python ../DataProject/Finnish/arff_transformer_with_attributes_list.py "../DataProject/data/Finnish/results/stemmed/$file_name" "../DataProject/data/Finnish/results/attributes/$file_name" "$file_name" > ../DataProject/data/Finnish/results/$file_name\_assoc.arff

#creates ARFF file for association rule testing
python ../DataProject/Finnish/clustering_arff_creator.py "../DataProject/data/Finnish/results/stemmed/$file_name" "../DataProject/data/Finnish/results/attributes/$file_name" "$file_name" > ../DataProject/data/Finnish/results/$file_name\_clustering.arff

