#!/bin/bash

#asks for filename
echo "Enter file name:"
read file_name

#creates stemmed file
cat data/Finnish/$file_name | python Finnish/preproc_Finland.py | python Finnish/finnish_stemmer.py > data/Finnish/results/stemmed/$file_name

#creates attribute list
cd Tools/FinnPos
cat ../../data/Finnish/$file_name | python ../../Finnish/Finntagger_preproc.py | ftb-label | python ../../Finnish/Finnish_nounfreq.py | python ../../Finnish/Finnish_attr_lister.py > ../../data/Finnish/results/attributes/$file_name
cd ..
cd ..

#creates ARFF file for association rule testing
python Finnish/arff_transformer_with_attributes_list.py "data/Finnish/results/stemmed/$file_name" "data/Finnish/results/attributes/$file_name" "$file_name" > data/Finnish/results/$file_name\_assoc.arff

#creates ARFF file for association rule testing
python Finnish/clustering_arff_creator.py "data/Finnish/results/stemmed/$file_name" "data/Finnish/results/attributes/$file_name" "$file_name" > data/Finnish/results/$file_name\_clustering.arff

