#!/bin/bash

#asks for filename
echo "Enter file name:"
read file_name

#creates frequency list
cd Tools/FinnPos
cat ../../data/Finnish/$file_name | python ../../freq/FIN/Finntagger_preproc.py | bin/ftb-label | python ../../freq/FIN/lemmas.py > ../../data/Finnish/results/freq/$file_name.freq


#creates noun frequency list
cat ../../data/Finnish/$file_name | python ../../freq/FIN/Finntagger_preproc.py | bin/ftb-label | python ../../freq/FIN/Finnish_nounfreq.py > ../../data/Finnish/results/freq/$file_name.nounfreq
cd ..
cd ..

